ignored = [
  "github.com/gopherjs/gopherjs/js",
]

required = [
  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/johanbrandhorst/protobuf/protoc-gen-gopherjs",
  "myitcv.io/react/cmd/reactGen",
  "myitcv.io/immutable/cmd/immutableGen",
  "github.com/foobaz/go-zopfli",
]

[prune]
  non-go = true
  unused-packages = true
  go-tests = true

  [[prune.project]]
    name = "github.com/johanbrandhorst/protobuf"
    non-go = false

  [[prune.project]]
    name = "myitcv.io/highlightjs"
    non-go = false

  [[prune.project]]
    name = "myitcv.io/react"
    non-go = false

  [[prune.project]]
    name = "github.com/gopherjs/jsbuiltin"
    non-go = false

[[constraint]]
  name = "github.com/johanbrandhorst/protobuf"
  version = "0.6.1"

[[constraint]]
  name = "github.com/improbable-eng/grpc-web"
  version = "0.6.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "honnef.co/go/js/xhr"

[[constraint]]
  branch = "master"
  name = "myitcv.io/highlightjs"

[[constraint]]
  branch = "master"
  name = "myitcv.io/immutable"

[[constraint]]
  branch = "master"
  name = "myitcv.io/react"
